server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 表示是否将注解注册进eureka server，默认为true
    register-with-eureka: true
    # 是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能实现负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka