server:
  port: 10801

spring:
  application:
    name: cloud-payment-service
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    # mysql驱动包
    url: jdbc:mysql://9.135.220.213:3306/cloudLearn?useUnicode=true&characterEncoding=UTF-8&useSSL=false&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: JxZah*7428Cp

eureka:
  client:
    # 表示是否将注解注册进eureka server，默认为true
    register-with-eureka: true
    # 是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能实现负载均衡
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:10701/eureka,http://localhost:10702/eureka # 集群情况下需要将所有eureka server写入

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coachhe.springcloud.entities